# Generated by Django 5.2.4 on 2025-08-31 14:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="earned_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="이 주문으로 적립된 포인트",
                verbose_name="적립 포인트",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="final_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="총 주문 금액 - 사용 포인트",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="최종 결제금액",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="used_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="이 주문에서 사용한 포인트",
                verbose_name="사용 포인트",
            ),
        ),
        migrations.CreateModel(
            name="PointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="양수는 적립, 음수는 사용/차감", verbose_name="포인트"
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        help_text="변경 후 포인트 잔액", verbose_name="잔액"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("earn", "적립"),
                            ("use", "사용"),
                            ("cancel_refund", "취소환불"),
                            ("cancel_deduct", "취소차감"),
                            ("expire", "만료"),
                            ("admin_add", "관리자지급"),
                            ("admin_deduct", "관리자차감"),
                            ("event", "이벤트"),
                        ],
                        max_length=20,
                        verbose_name="타입",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="포인트 변동 사유",
                        max_length=255,
                        verbose_name="설명",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="적립 포인트의 유효기간",
                        null=True,
                        verbose_name="만료일시",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="추가 정보 (JSON)",
                        verbose_name="메타데이터",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_histories",
                        to="shopping.order",
                        verbose_name="관련 주문",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트 이력",
                "verbose_name_plural": "포인트 이력 목록",
                "db_table": "shopping_point_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="shopping_po_user_id_726970_idx",
                    ),
                    models.Index(fields=["type"], name="shopping_po_type_32f15d_idx"),
                    models.Index(
                        fields=["order"], name="shopping_po_order_i_f0debd_idx"
                    ),
                ],
            },
        ),
    ]
