# Generated by Django 5.2.4 on 2025-09-12 16:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_order_earned_points_order_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_shipping_fee',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='제주/도서산간 등 추가 배송비', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='추가 배송비'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_free_shipping',
            field=models.BooleanField(default=False, help_text='무료배송 적용 여부', verbose_name='무료배송 여부'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='기본 배송비', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='배송비'),
        ),
    ]
