# Generated by Django 5.2.4 on 2025-09-23 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_order_additional_shipping_fee_order_is_free_shipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='인증 토큰')),
                ('verification_code', models.CharField(editable=False, max_length=6, verbose_name='인증 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이메일 인증 토큰',
                'verbose_name_plural': '이메일 인증 토큰',
                'db_table': 'email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('verification', '이메일 인증'), ('password_reset', '비밀번호 재설정'), ('order_confirm', '주문 확인'), ('marketing', '마케팅')], max_length=20, verbose_name='이메일 유형')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='수신자 이메일')),
                ('subject', models.CharField(max_length=255, verbose_name='제목')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('sent', '발송완료'), ('failed', '발송실패'), ('opened', '열람됨'), ('clicked', '클릭됨'), ('verified', '인증완료')], default='pending', max_length=20, verbose_name='상태')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='열람일시')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='클릭일시')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증완료일시')),
                ('error_message', models.TextField(blank=True, verbose_name='에러 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='shopping.emailverificationtoken', verbose_name='인증 토큰')),
            ],
            options={
                'verbose_name': '이메일 로그',
                'verbose_name_plural': '이메일 로그',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token'], name='email_verif_token_df7c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['verification_code', 'user'], name='email_verif_verific_d95590_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['created_at'], name='email_verif_created_bb4dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', 'email_type'], name='email_logs_user_id_15a69f_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='email_logs_status_e3be55_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['created_at'], name='email_logs_created_76afc3_idx'),
        ),
    ]
