# Generated by Django 5.2.4 on 2025-08-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_alter_product_seller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="sesstion_key",
            new_name="session_key",
        ),
    ]
