# Generated by Django 5.2.4 on 2025-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_emailverificationtoken_emaillog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist_products',
            field=models.ManyToManyField(blank=True, db_table='shopping_wishlist', related_name='wished_by_users', to='shopping.product', verbose_name='찜한 상품'),
        ),
    ]
