# Generated by Django 5.2.4 on 2025-10-18 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_user_wishlist_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('is_secret', models.BooleanField(default=False, help_text='체크 시 작성자와 판매자만 볼 수 있습니다', verbose_name='비밀글')),
                ('is_answered', models.BooleanField(db_index=True, default=False, verbose_name='답변 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shopping.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '상품 문의',
                'verbose_name_plural': '상품 문의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='답변일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_answers', to=settings.AUTH_USER_MODEL, verbose_name='답변자')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='shopping.productquestion', verbose_name='문의')),
            ],
            options={
                'verbose_name': '문의 답변',
                'verbose_name_plural': '문의 답변',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('qa_answer', '상품 문의 답변'), ('order_status', '주문 상태 변경'), ('point_earned', '포인트 적립'), ('point_expiring', '포인트 만료 예정'), ('review_reply', '리뷰 답글')], max_length=20, verbose_name='알림 타입')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('link', models.CharField(blank=True, help_text='클릭 시 이동할 URL (예: /products/123/questions/45)', max_length=200, null=True, verbose_name='링크')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='shopping_no_user_id_089332_idx'), models.Index(fields=['user', 'is_read'], name='shopping_no_user_id_fd5be4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productquestion',
            index=models.Index(fields=['product', '-created_at'], name='shopping_pr_product_9e58fa_idx'),
        ),
        migrations.AddIndex(
            model_name='productquestion',
            index=models.Index(fields=['user', '-created_at'], name='shopping_pr_user_id_9f756a_idx'),
        ),
        migrations.AddIndex(
            model_name='productquestion',
            index=models.Index(fields=['is_answered'], name='shopping_pr_is_answ_938b81_idx'),
        ),
    ]
