# Generated by Django 5.2.4 on 2025-08-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shopping",
            "0005_alter_category_options_category_level_category_lft_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="주문번호"
            ),
        ),
    ]
