# Generated by Django 5.2.4 on 2025-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0006_productquestion_productanswer_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "결제대기"),
                    ("paid", "결제완료"),
                    ("preparing", "배송준비중"),
                    ("shipped", "배송중"),
                    ("delivered", "배송완료"),
                    ("canceled", "주문취소"),
                    ("refunded", "환불완료"),
                ],
                default="pending",
                max_length=20,
                verbose_name="주문상태",
            ),
        ),
    ]
