# Generated by Django 5.2.4 on 2025-08-14 16:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0006_order_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_key",
                    models.CharField(
                        blank=True,
                        help_text="토스페이먼츠에서 발급한 고유 결제키",
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="토스 결제키",
                    ),
                ),
                (
                    "toss_order_id",
                    models.CharField(
                        help_text="우리 시스템의 주문번호",
                        max_length=100,
                        unique=True,
                        verbose_name="토스 주문번호",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="결제 금액"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="카드, 계좌이체, 가상계좌 등",
                        max_length=50,
                        verbose_name="결제 수단",
                    ),
                ),
                (
                    "card_company",
                    models.CharField(blank=True, max_length=50, verbose_name="카드사"),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        help_text="마스킹된 카드번호",
                        max_length=30,
                        verbose_name="카드번호",
                    ),
                ),
                (
                    "installment_plan_months",
                    models.IntegerField(
                        default=0, help_text="0은 일시불", verbose_name="할부 개월수"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "결제 준비"),
                            ("in_progress", "결제 진행중"),
                            ("waiting_for_deposit", "입금 대기"),
                            ("done", "결제 완료"),
                            ("canceled", "결제 취소"),
                            ("partial_canceled", "부분 취소"),
                            ("aborted", "결제 실패"),
                            ("expired", "결제 만료"),
                        ],
                        default="ready",
                        max_length=30,
                        verbose_name="결제 상태",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인 일시"
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="영수증 URL"
                    ),
                ),
                (
                    "is_canceled",
                    models.BooleanField(default=False, verbose_name="취소 여부"),
                ),
                (
                    "canceled_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="취소 금액",
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="취소 사유"),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="취소 일시"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="토스페이먼츠 API 응답 전체",
                        verbose_name="토스 응답 원본",
                    ),
                ),
                ("fail_reason", models.TextField(blank=True, verbose_name="실패 사유")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="shopping.order",
                        verbose_name="주문",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제",
                "verbose_name_plural": "결제 목록",
                "db_table": "shopping_paments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("request", "결제 요청"),
                            ("approve", "결제 승인"),
                            ("cancel", "결제 취소"),
                            ("webhook", "웹훅 수신"),
                            ("error", "에러 발생"),
                        ],
                        max_length=20,
                        verbose_name="로그 타입",
                    ),
                ),
                ("message", models.TextField(verbose_name="로그 메시지")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="추가 데이터"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="shopping.payment",
                        verbose_name="결제",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 로그",
                "verbose_name_plural": "결제 로그 목록",
                "db_table": "shopping_payment_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_key"], name="shopping_pa_payment_c44b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order_id"], name="shopping_pa_order_i_a21379_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="shopping_pa_status_181d8f_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-created_at"], name="shopping_pa_created_ae8071_idx"
            ),
        ),
    ]
