# Generated by Django 5.2.4 on 2025-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0007_payment_paymentlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(
                default="주소 미입력",
                help_text="기본 주소 (도로명 또는 지번)",
                max_length=200,
                verbose_name="배송 주소",
            ),
            preserve_default=False,
        ),
    ]
