# Generated by Django 5.2.4 on 2025-10-29 16:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("qa_answer", "상품 문의 답변"),
                    ("order_status", "주문 상태 변경"),
                    ("point_earned", "포인트 적립"),
                    ("point_expiring", "포인트 만료 예정"),
                    ("review_reply", "리뷰 답글"),
                    ("return", "교환/환불"),
                ],
                max_length=20,
                verbose_name="알림 타입",
            ),
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "return_number",
                    models.CharField(
                        help_text="자동 생성됨 (예: RET20250115001)", max_length=50, unique=True, verbose_name="교환/환불 번호"
                    ),
                ),
                (
                    "type",
                    models.CharField(choices=[("refund", "환불"), ("exchange", "교환")], max_length=10, verbose_name="타입"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "신청"),
                            ("approved", "승인"),
                            ("rejected", "거부"),
                            ("shipping", "반품배송중"),
                            ("received", "반품도착"),
                            ("completed", "완료"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("change_of_mind", "단순변심"),
                            ("defective", "상품불량"),
                            ("wrong_product", "오배송"),
                            ("description_mismatch", "상세페이지와 다름"),
                            ("size_issue", "사이즈 문제"),
                            ("other", "기타"),
                        ],
                        max_length=30,
                        verbose_name="사유",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(help_text="교환/환불 사유를 구체적으로 작성해주세요", verbose_name="상세 사유"),
                ),
                (
                    "return_shipping_company",
                    models.CharField(
                        blank=True, help_text="예: CJ대한통운, 우체국택배", max_length=50, verbose_name="반품 택배사"
                    ),
                ),
                ("return_tracking_number", models.CharField(blank=True, max_length=50, verbose_name="반품 송장번호")),
                (
                    "return_shipping_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        help_text="고객 부담인 경우 금액 입력",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="반품 배송비",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="환불 금액",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True, help_text="원결제수단 또는 계좌환불", max_length=20, verbose_name="환불 방법"
                    ),
                ),
                ("refund_account_bank", models.CharField(blank=True, max_length=50, verbose_name="환불 계좌 은행")),
                ("refund_account_number", models.CharField(blank=True, max_length=50, verbose_name="환불 계좌번호")),
                ("refund_account_holder", models.CharField(blank=True, max_length=50, verbose_name="예금주")),
                ("exchange_shipping_company", models.CharField(blank=True, max_length=50, verbose_name="교환 상품 택배사")),
                ("exchange_tracking_number", models.CharField(blank=True, max_length=50, verbose_name="교환 상품 송장번호")),
                ("admin_memo", models.TextField(blank=True, help_text="내부용 메모", verbose_name="관리자 메모")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="승인 시각")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="완료 시각")),
                ("rejected_reason", models.TextField(blank=True, verbose_name="거부 사유")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="신청일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "exchange_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="교환받을 상품 (같은 상품일 수도 있음)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exchange_returns",
                        to="shopping.product",
                        verbose_name="교환 상품",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="shopping.order",
                        verbose_name="원본 주문",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "교환/환불",
                "verbose_name_plural": "교환/환불 목록",
                "db_table": "shopping_returns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="반품 수량"
                    ),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="상품명")),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="단가",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="등록일")),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_items",
                        to="shopping.orderitem",
                        verbose_name="주문 상품",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_items",
                        to="shopping.return",
                        verbose_name="교환/환불 신청",
                    ),
                ),
            ],
            options={
                "verbose_name": "반품 상품",
                "verbose_name_plural": "반품 상품 목록",
                "db_table": "shopping_return_items",
            },
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["return_number"], name="shopping_re_return__b44a3f_idx"),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["user", "-created_at"], name="shopping_re_user_id_65e8c5_idx"),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["order"], name="shopping_re_order_i_a6c351_idx"),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["status"], name="shopping_re_status_ebe471_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="returnitem",
            unique_together={("return_request", "order_item")},
        ),
    ]
