# Generated by Django 5.2.4 on 2025-08-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0008_order_shipping_address"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_payment_310c34_idx",
            old_name="shopping_pa_payment_c44b6e_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_order_i_98bb42_idx",
            old_name="shopping_pa_order_i_a21379_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_status_d521a5_idx",
            old_name="shopping_pa_status_181d8f_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_created_a720fb_idx",
            old_name="shopping_pa_created_ae8071_idx",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="shopping_pament",
        ),
    ]
