# Generated by Django 5.2.4 on 2025-10-31 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0008_alter_notification_notification_type_return_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="재설정 토큰")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("is_used", models.BooleanField(default=False, verbose_name="사용 여부")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="사용일시")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "비밀번호 재설정 토큰",
                "verbose_name_plural": "비밀번호 재설정 토큰",
                "db_table": "password_reset_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="password_re_token_060a1f_idx"),
                    models.Index(fields=["user", "is_used"], name="password_re_user_id_cd37a3_idx"),
                    models.Index(fields=["created_at"], name="password_re_created_265757_idx"),
                ],
            },
        ),
    ]
