# Generated by Django 5.2.4 on 2025-08-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "shopping",
            "0009_rename_shopping_pa_payment_c44b6e_idx_shopping_pa_payment_310c34_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_payment_02a634_idx",
            old_name="shopping_pa_payment_310c34_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_order_i_18c3ab_idx",
            old_name="shopping_pa_order_i_98bb42_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_status_bfdd12_idx",
            old_name="shopping_pa_status_d521a5_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="shopping_pa_created_56f063_idx",
            old_name="shopping_pa_created_a720fb_idx",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="shopping_payment",
        ),
    ]
