# Generated by Django 5.2.4 on 2025-11-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0009_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(
                default=False, help_text="체크 시 상품 등록/관리 및 교환/환불 처리 권한 부여", verbose_name="판매자 여부"
            ),
        ),
    ]
