# Generated by Django 5.2.4 on 2025-11-21 16:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0010_user_is_seller"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name": "카테고리", "verbose_name_plural": "카테고리"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["id"], "verbose_name": "주문 상품", "verbose_name_plural": "주문 상품 목록"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"], "verbose_name": "사용자", "verbose_name_plural": "사용자 목록"},
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_active_cart_per_user",
        ),
        migrations.RemoveIndex(
            model_name="passwordresettoken",
            name="password_re_token_060a1f_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="shopping_pa_payment_02a634_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="shopping_pa_toss_or_213453_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="shopping_pa_status_bfdd12_idx",
        ),
        migrations.RemoveIndex(
            model_name="return",
            name="shopping_re_return__b44a3f_idx",
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="token",
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="token_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="토큰의 SHA-256 해시값 (보안을 위해 평문 저장하지 않음)",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="토큰 해시",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="현재 사용중인 장바구니인지 여부", verbose_name="활성 상태"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="비회원 장바구니를 위한 세션 키",
                max_length=255,
                null=True,
                verbose_name="세션 키",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="회원 장바구니의 경우 사용자 정보",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shopping.product",
                verbose_name="상품",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="활성화 여부"),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="clicked_at",
            field=models.DateTimeField(
                blank=True, help_text="이메일 내 링크가 클릭된 일시", null=True, verbose_name="클릭일시"
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("verification", "이메일 인증"),
                    ("password_reset", "비밀번호 재설정"),
                    ("order_confirm", "주문 확인"),
                    ("marketing", "마케팅"),
                ],
                help_text="발송된 이메일의 유형",
                max_length=20,
                verbose_name="이메일 유형",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="error_message",
            field=models.TextField(blank=True, default="", help_text="발송 실패 시 에러 메시지", verbose_name="에러 메시지"),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="opened_at",
            field=models.DateTimeField(blank=True, help_text="이메일이 열람된 일시", null=True, verbose_name="열람일시"),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="recipient_email",
            field=models.EmailField(
                db_index=True, help_text="이메일 수신자 주소", max_length=254, verbose_name="수신자 이메일"
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="sent_at",
            field=models.DateTimeField(blank=True, help_text="이메일이 발송된 일시", null=True, verbose_name="발송일시"),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("sent", "발송완료"),
                    ("failed", "발송실패"),
                    ("opened", "열람됨"),
                    ("clicked", "클릭됨"),
                    ("verified", "인증완료"),
                ],
                default="pending",
                help_text="이메일 발송 상태 (pending → sent → opened/clicked → verified)",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="subject",
            field=models.CharField(help_text="이메일 제목", max_length=255, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="token",
            field=models.ForeignKey(
                blank=True,
                help_text="연결된 이메일 인증 토큰 (인증 이메일인 경우)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="shopping.emailverificationtoken",
                verbose_name="인증 토큰",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="user",
            field=models.ForeignKey(
                help_text="이메일을 수신한 사용자 (탈퇴 시에도 로그 보존)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="verified_at",
            field=models.DateTimeField(blank=True, help_text="인증이 완료된 일시", null=True, verbose_name="인증완료일시"),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="is_used",
            field=models.BooleanField(
                default=False, help_text="토큰 사용 여부 (True: 사용됨, False: 미사용)", verbose_name="사용 여부"
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="이메일 링크에 사용되는 UUID 토큰 (URL-safe)",
                unique=True,
                verbose_name="인증 토큰",
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="used_at",
            field=models.DateTimeField(blank=True, help_text="토큰이 사용된 일시", null=True, verbose_name="사용일시"),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="user",
            field=models.ForeignKey(
                help_text="인증 토큰을 소유한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="verification_code",
            field=models.CharField(
                editable=False, help_text="6자리 영문 대문자 + 숫자 조합 (직접 입력용)", max_length=6, verbose_name="인증 코드"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.CharField(
                blank=True,
                default="",
                help_text="클릭 시 이동할 URL (예: /products/123/questions/45)",
                max_length=200,
                verbose_name="링크",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_memo",
            field=models.TextField(blank=True, default="", help_text="배송 시 요청사항", verbose_name="주문메모"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="자동 생성되는 고유 주문번호",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="주문번호",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "신용/체크카드"),
                    ("bank_transfer", "무통장입금"),
                    ("kakao_pay", "카카오페이"),
                    ("naver_pay", "네이버페이"),
                    ("toss", "토스"),
                ],
                default="",
                help_text="결제 완료 후 자동 입력됨",
                max_length=20,
                verbose_name="결제방법",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address_detail",
            field=models.CharField(
                blank=True, default="", help_text="동/호수 등 상세 주소 (선택사항)", max_length=255, verbose_name="상세주소"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_postal_code",
            field=models.CharField(help_text="5자리 우편번호", max_length=10, verbose_name="우편번호"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "결제대기"),
                    ("confirmed", "주문확정"),
                    ("paid", "결제완료"),
                    ("preparing", "배송준비중"),
                    ("shipped", "배송중"),
                    ("delivered", "배송완료"),
                    ("canceled", "주문취소"),
                    ("refunded", "환불완료"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="주문상태",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="shopping.product",
                verbose_name="상품",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="토큰이 생성된 시각", verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="is_used",
            field=models.BooleanField(
                default=False, help_text="토큰 사용 여부 (사용 시 자동으로 True)", verbose_name="사용 여부"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="used_at",
            field=models.DateTimeField(blank=True, help_text="토큰이 실제로 사용된 시각", null=True, verbose_name="사용일시"),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                help_text="비밀번호를 재설정할 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="installment_plan_months",
            field=models.IntegerField(
                default=0,
                help_text="0은 일시불, 최대 60개월",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)],
                verbose_name="할부 개월수",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="체크 해제시 상품이 숨겨집니다.", verbose_name="판매중"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="판매자",
            ),
        ),
        migrations.AlterField(
            model_name="productanswer",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="탈퇴한 판매자의 답변은 보존됩니다",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="답변자",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=False, verbose_name="대표 이미지"),
        ),
        migrations.AlterField(
            model_name="productquestion",
            name="is_answered",
            field=models.BooleanField(default=False, verbose_name="답변 완료"),
        ),
        migrations.AlterField(
            model_name="productquestion",
            name="product",
            field=models.ForeignKey(
                help_text="문의가 있는 상품은 삭제할 수 없습니다",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="shopping.product",
                verbose_name="상품",
            ),
        ),
        migrations.AlterField(
            model_name="productquestion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="탈퇴한 사용자의 문의는 보존됩니다",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="admin_memo",
            field=models.TextField(
                blank=True,
                help_text="⚠️ 내부용 메모 - 고객에게 노출되어선 안 됨 (Serializer/View에서 관리자만 조회 가능하도록 설정 필요)",
                verbose_name="관리자 메모",
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="refund_account_number",
            field=models.TextField(
                blank=True,
                help_text="암호화되어 저장됩니다. 복호화는 get_decrypted_account_number() 사용",
                verbose_name="환불 계좌번호 (암호화)",
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="user",
            field=models.ForeignKey(
                help_text="사용자 탈퇴 시에도 교환/환불 기록 유지 (법적 보존 의무)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="신청자",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="체크 시 상품 등록/관리 및 교환/환불 처리 권한 부여",
                verbose_name="판매자 여부",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_withdrawn",
            field=models.BooleanField(db_index=True, default=False, verbose_name="탈퇴 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="membership_level",
            field=models.CharField(
                choices=[("bronze", "브론즈"), ("silver", "실버"), ("gold", "골드"), ("vip", "VIP")],
                db_index=True,
                default="bronze",
                max_length=10,
                verbose_name="회원등급",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["-updated_at"], name="shopping_ca_updated_0ef5b0_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["-added_at"], name="shopping_ca_added_a_d6ea9b_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["is_used", "created_at"], name="email_verif_is_used_ee6186_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "-created_at"], name="shopping_or_status_6420ba_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "-created_at"], name="shopping_or_user_id_80d808_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_number"], name="shopping_or_order_n_0ddc42_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "-created_at"], name="shopping_pa_status_3f8851_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(fields=["payment", "-created_at"], name="shopping_pa_payment_80e9e6_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(fields=["log_type"], name="shopping_pa_log_typ_cd77c4_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(fields=["-created_at"], name="shopping_pa_created_1e46b4_idx"),
        ),
        migrations.AddIndex(
            model_name="pointhistory",
            index=models.Index(fields=["expires_at"], name="shopping_po_expires_47ad27_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-created_at"], name="shopping_pr_created_c4b162_idx"),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("user__isnull", False)),
                fields=("user",),
                name="unique_active_cart_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("session_key__isnull", False)),
                fields=("session_key",),
                name="unique_active_cart_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailverificationtoken",
            constraint=models.UniqueConstraint(fields=("user", "verification_code"), name="unique_user_verification_code"),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)), fields=("product",), name="unique_primary_image_per_product"
            ),
        ),
    ]
