# Generated by Django 5.2.4 on 2025-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shopping",
            "0010_rename_shopping_pa_payment_310c34_idx_shopping_pa_payment_02a634_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="shopping_pa_order_i_18c3ab_idx",
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["toss_order_id"], name="shopping_pa_toss_or_213453_idx"
            ),
        ),
    ]
