# Generated by Django 5.2.4 on 2025-11-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0011_alter_category_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="failure_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="주문 실패 시 상세 사유 (재고 부족, 포인트 부족 등)",
                verbose_name="실패 사유",
            ),
        ),
    ]
