# Generated by Django 5.2.4 on 2025-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0012_order_failure_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "이미 사용중인 이메일입니다."},
                max_length=254,
                unique=True,
                verbose_name="이메일 주소",
            ),
        ),
    ]
