# Generated by Django 5.2.4 on 2025-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0013_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="알림 관련 추가 데이터 (예: return_id, order_id 등)",
                verbose_name="메타데이터",
            ),
        ),
    ]
